# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: node:10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: install tooling
        run: |
          echo install ,
          echo test, and deploy your project
          apt-get update
          apt-get -y install curl
          curl -sL https://deb.nodesource.com/setup_10.x | bash -
          apt-get install -y nodejs
          npm install npm
          npm install -g particle-cli
          
      # Runs a set of commands using the runners shell
      - name: building code
        run: |
          particle -q login -u $PARTICLE_USR -p  $PARTICLE_PWD
          particle compile photon --target 0.7.0
      - name: deploy
        run: particle flash $PARTICLE_DEVICE_NAME *.bin
